# Form implementation generated from reading ui file 'tab7.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab7_frame(object):
    def setupUi(self, tab7_frame):
        tab7_frame.setObjectName("tab7_frame")
        tab7_frame.resize(911, 584)
        self.centralwidget = QtWidgets.QWidget(parent=tab7_frame)
        self.centralwidget.setStyleSheet("/* ===== 浅色主题基础 ===== */\n"
"QWidget#centralwidget { background:#f5f6f8; color:#333; font-family:\"Microsoft YaHei UI\"; }\n"
"\n"
"/* 卡片容器 */\n"
"QFrame#status_frame, QFrame#graphic_frame { background:#ffffff; border:1px solid #dcdfe3; border-radius:10px; }\n"
"\n"
"/* 文本组件 */\n"
"QTextBrowser, QPlainTextEdit { background:#ffffff; border:1px solid #d2d5da; border-radius:6px; padding:4px; font-size:10pt; }\n"
"QTextBrowser .warn { color:#d48806; }\n"
"QTextBrowser .error { color:#d32029; }\n"
"\n"
"/* 标题/标签 */\n"
"QLabel#label, QLabel#video_slider_text { font-weight:600; letter-spacing:0.5px; color:#555; }\n"
"\n"
"/* 按钮 */\n"
"QPushButton { background:#2F6FEB; border:1px solid #2a62d6; border-radius:6px; color:#fff; padding:5px 16px; font-size:10pt; }\n"
"QPushButton:hover { background:#4785ff; }\n"
"QPushButton:pressed { background:#1d4fa8; }\n"
"QPushButton:disabled { background:#c5ccd4; color:#ffffff; }\n"
"\n"
"/* 滑块 */\n"
"QSlider::groove:horizontal { height:6px; background:#dcdfe3; border-radius:3px; }\n"
"QSlider::handle:horizontal { background:#2F6FEB; width:16px; height:16px; margin:-5px 0; border-radius:8px; border:1px solid #2a62d6; }\n"
"QSlider::handle:horizontal:hover { background:#4785ff; }\n"
"\n"
"/* 分隔线 */\n"
"QFrame#line { border:none; background:#dcdfe3; max-height:1px; }\n"
"\n"
"/* 状态栏 */\n"
"QStatusBar { background:#ffffff; border-top:1px solid #dcdfe3; }\n"
"\n"
"/* 滚动区域透明背景 */\n"
"QScrollArea { border:0; background:transparent; }\n"
"QScrollArea QWidget { background:transparent; }\n"
"/* Modern Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal { background:transparent; width:10px; height:10px; margin:0; }\n"
"QScrollBar::handle { background:#c2c7ce; border-radius:5px; min-height:20px; min-width:20px; }\n"
"QScrollBar::handle:hover { background:#aab1ba; }\n"
"QScrollBar::handle:pressed { background:#8d949c; }\n"
"QScrollBar::add-line, QScrollBar::sub-line { background:transparent; width:0; height:0; }\n"
"QScrollBar::add-page, QScrollBar::sub-page { background:transparent; }\n"
"   ")
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.left_panel = QtWidgets.QWidget(parent=self.centralwidget)
        self.left_panel.setObjectName("left_panel")
        self.left_panel_layout = QtWidgets.QVBoxLayout(self.left_panel)
        self.left_panel_layout.setObjectName("left_panel_layout")
        self.scrollArea_path = QtWidgets.QScrollArea(parent=self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_path.sizePolicy().hasHeightForWidth())
        self.scrollArea_path.setSizePolicy(sizePolicy)
        self.scrollArea_path.setMaximumHeight(70)
        self.scrollArea_path.setMinimumSize(QtCore.QSize(0, 30))
        self.scrollArea_path.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea_path.setWidgetResizable(True)
        self.scrollArea_path.setObjectName("scrollArea_path")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 352, 70))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_path_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea_path_layout.setObjectName("scrollArea_path_layout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.scrollArea_path_layout.addWidget(self.plainTextEdit)
        self.scrollArea_path.setWidget(self.scrollAreaWidgetContents)
        self.left_panel_layout.addWidget(self.scrollArea_path)
        self.media_stack = QtWidgets.QStackedWidget(parent=self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.media_stack.sizePolicy().hasHeightForWidth())
        self.media_stack.setSizePolicy(sizePolicy)
        self.media_stack.setObjectName("media_stack")
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.image_page_layout = QtWidgets.QVBoxLayout(self.image_page)
        self.image_page_layout.setObjectName("image_page_layout")
        self.image_canvas = QtWidgets.QLabel(parent=self.image_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.image_canvas.sizePolicy().hasHeightForWidth())
        self.image_canvas.setSizePolicy(sizePolicy)
        self.image_canvas.setMinimumSize(QtCore.QSize(0, 260))
        self.image_canvas.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_canvas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_canvas.setObjectName("image_canvas")
        self.image_page_layout.addWidget(self.image_canvas)
        self.image_toolbar_layout = QtWidgets.QHBoxLayout()
        self.image_toolbar_layout.setObjectName("image_toolbar_layout")
        self.image_prev_btn = QtWidgets.QPushButton(parent=self.image_page)
        self.image_prev_btn.setObjectName("image_prev_btn")
        self.image_toolbar_layout.addWidget(self.image_prev_btn)
        self.image_next_btn = QtWidgets.QPushButton(parent=self.image_page)
        self.image_next_btn.setObjectName("image_next_btn")
        self.image_toolbar_layout.addWidget(self.image_next_btn)
        self.image_refresh_btn = QtWidgets.QPushButton(parent=self.image_page)
        self.image_refresh_btn.setObjectName("image_refresh_btn")
        self.image_toolbar_layout.addWidget(self.image_refresh_btn)
        self.image_test_btn = QtWidgets.QPushButton(parent=self.image_page)
        self.image_test_btn.setObjectName("image_test_btn")
        self.image_toolbar_layout.addWidget(self.image_test_btn)
        self.image_device_label = QtWidgets.QLabel(parent=self.image_page)
        self.image_device_label.setText("")
        self.image_device_label.setObjectName("image_device_label")
        self.image_toolbar_layout.addWidget(self.image_device_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.image_toolbar_layout.addItem(spacerItem)
        self.image_device_combo = QtWidgets.QComboBox(parent=self.image_page)
        self.image_device_combo.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.image_device_combo.setObjectName("image_device_combo")
        self.image_toolbar_layout.addWidget(self.image_device_combo)
        self.image_page_layout.addLayout(self.image_toolbar_layout)
        self.media_stack.addWidget(self.image_page)
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.video_page_layout = QtWidgets.QVBoxLayout(self.video_page)
        self.video_page_layout.setObjectName("video_page_layout")
        self.video_container = QtWidgets.QWidget(parent=self.video_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.video_container.sizePolicy().hasHeightForWidth())
        self.video_container.setSizePolicy(sizePolicy)
        self.video_container.setObjectName("video_container")
        self.video_layout = QtWidgets.QVBoxLayout(self.video_container)
        self.video_layout.setObjectName("video_layout")
        self.video_page_layout.addWidget(self.video_container)
        self.slider_row = QtWidgets.QHBoxLayout()
        self.slider_row.setObjectName("slider_row")
        self.video_slider = QtWidgets.QSlider(parent=self.video_page)
        self.video_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.slider_row.addWidget(self.video_slider)
        self.video_slider_text = QtWidgets.QLabel(parent=self.video_page)
        self.video_slider_text.setObjectName("video_slider_text")
        self.slider_row.addWidget(self.video_slider_text)
        self.video_page_layout.addLayout(self.slider_row)
        self.video_btn_layout = QtWidgets.QHBoxLayout()
        self.video_btn_layout.setObjectName("video_btn_layout")
        self.open_video_btn = QtWidgets.QPushButton(parent=self.video_page)
        self.open_video_btn.setObjectName("open_video_btn")
        self.video_btn_layout.addWidget(self.open_video_btn)
        self.start_video_btn = QtWidgets.QPushButton(parent=self.video_page)
        self.start_video_btn.setObjectName("start_video_btn")
        self.video_btn_layout.addWidget(self.start_video_btn)
        self.stop_video_btn = QtWidgets.QPushButton(parent=self.video_page)
        self.stop_video_btn.setObjectName("stop_video_btn")
        self.video_btn_layout.addWidget(self.stop_video_btn)
        self.video_page_layout.addLayout(self.video_btn_layout)
        self.media_stack.addWidget(self.video_page)
        self.left_panel_layout.addWidget(self.media_stack)
        self.left_panel_layout.setStretch(1, 1)
        self.top_layout.addWidget(self.left_panel)
        self.graphic_frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_frame.sizePolicy().hasHeightForWidth())
        self.graphic_frame.setSizePolicy(sizePolicy)
        self.graphic_frame.setMinimumSize(QtCore.QSize(600, 400))
        self.graphic_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graphic_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graphic_frame.setObjectName("graphic_frame")
        self.charts_layout = QtWidgets.QVBoxLayout(self.graphic_frame)
        self.charts_layout.setObjectName("charts_layout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.graphic_frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidget = QtWidgets.QWidget()
        self.scrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 511, 380))
        self.scrollAreaWidget.setObjectName("scrollAreaWidget")
        self.scrollArea.setWidget(self.scrollAreaWidget)
        self.charts_layout.addWidget(self.scrollArea)
        self.top_layout.addWidget(self.graphic_frame)
        self.top_layout.setStretch(0, 2)
        self.top_layout.setStretch(1, 3)
        self.main_layout.addLayout(self.top_layout)
        self.status_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.status_frame.setMaximumHeight(220)
        self.status_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.status_frame.setObjectName("status_frame")
        self.status_main_vlayout = QtWidgets.QVBoxLayout(self.status_frame)
        self.status_main_vlayout.setObjectName("status_main_vlayout")
        self.status_header_layout = QtWidgets.QHBoxLayout()
        self.status_header_layout.setObjectName("status_header_layout")
        self.label = QtWidgets.QLabel(parent=self.status_frame)
        self.label.setObjectName("label")
        self.status_header_layout.addWidget(self.label)
        self.line = QtWidgets.QFrame(parent=self.status_frame)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.status_header_layout.addWidget(self.line)
        self.status_main_vlayout.addLayout(self.status_header_layout)
        self.status_content_layout = QtWidgets.QHBoxLayout()
        self.status_content_layout.setObjectName("status_content_layout")
        self.statusBrowser = QtWidgets.QTextBrowser(parent=self.status_frame)
        self.statusBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.statusBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.statusBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.statusBrowser.setObjectName("statusBrowser")
        self.status_content_layout.addWidget(self.statusBrowser)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.openFL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openFL_btn.setObjectName("openFL_btn")
        self.buttons_layout.addWidget(self.openFL_btn)
        self.openYL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openYL_btn.setObjectName("openYL_btn")
        self.buttons_layout.addWidget(self.openYL_btn)
        self.openSL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openSL_btn.setObjectName("openSL_btn")
        self.buttons_layout.addWidget(self.openSL_btn)
        self.openReport_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openReport_btn.setObjectName("openReport_btn")
        self.buttons_layout.addWidget(self.openReport_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.buttons_layout.addItem(spacerItem1)
        self.status_content_layout.addLayout(self.buttons_layout)
        self.status_main_vlayout.addLayout(self.status_content_layout)
        self.main_layout.addWidget(self.status_frame)
        tab7_frame.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=tab7_frame)
        self.statusbar.setObjectName("statusbar")
        tab7_frame.setStatusBar(self.statusbar)
        self.action123132 = QtGui.QAction(parent=tab7_frame)
        self.action123132.setObjectName("action123132")

        self.retranslateUi(tab7_frame)
        QtCore.QMetaObject.connectSlotsByName(tab7_frame)

    def retranslateUi(self, tab7_frame):
        _translate = QtCore.QCoreApplication.translate
        tab7_frame.setWindowTitle(_translate("tab7_frame", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("tab7_frame", "Path/to/file"))
        self.image_canvas.setText(_translate("tab7_frame", "暂无图片"))
        self.image_prev_btn.setText(_translate("tab7_frame", "上一张"))
        self.image_next_btn.setText(_translate("tab7_frame", "下一张"))
        self.image_refresh_btn.setText(_translate("tab7_frame", "刷新"))
        self.image_test_btn.setText(_translate("tab7_frame", "开始识别"))
        self.video_slider_text.setText(_translate("tab7_frame", "00:00/00:00"))
        self.open_video_btn.setText(_translate("tab7_frame", "打开视频"))
        self.start_video_btn.setText(_translate("tab7_frame", "开始播放"))
        self.stop_video_btn.setText(_translate("tab7_frame", "暂停播放"))
        self.label.setText(_translate("tab7_frame", "状态栏："))
        self.statusBrowser.setHtml(_translate("tab7_frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\\n</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">\\n</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.openFL_btn.setText(_translate("tab7_frame", "打开蜚蠊存档文件夹"))
        self.openYL_btn.setText(_translate("tab7_frame", "打开蝇类存档文件夹"))
        self.openSL_btn.setText(_translate("tab7_frame", "打开鼠类存档文件夹"))
        self.openReport_btn.setText(_translate("tab7_frame", "打开报告"))
        self.action123132.setText(_translate("tab7_frame", "123132"))
